service: ${env:NAME, file(./package.json):name}
variablesResolutionMode: 20210326
custom:
  local_env: ${sls:stage, 'test'}
  customDomain:
    domainName: ${env:SWAGGER, file(./.env/env.${self:custom.local_env}.json):SWAGGER}
    basePath: ''
    stage: ${sls:stage}
    createRoute53Record: true
  apigwBinary:
    types:
      - 'multipart/form-data'
      - 'image/jpeg'
      - 'image/png'
provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  timeout: 30
  lambdaHashingVersion: 20201221
  environment:
    NODE_ENV: ${env:NODE_ENV, file(./.env/env.${self:custom.local_env}.json):NODE_ENV}
    SWAGGER: ${env:SWAGGER, file(./.env/env.${self:custom.local_env}.json):SWAGGER}
    PROTOCOL: ${env:PROTOCOL, file(./.env/env.${self:custom.local_env}.json):PROTOCOL}
    MONGO: ${env:MONGO, file(./.env/env.${self:custom.local_env}.json):MONGO}
    REPLICA: ${env:REPLICA, file(./.env/env.${self:custom.local_env}.json):REPLICA}
    PERSIST_HTTP_ERRORS: ${env:PERSIST_HTTP_ERRORS, file(./.env/env.${self:custom.local_env}.json):PERSIST_HTTP_ERRORS}
    WRITE_LOGS_TO_DB: ${env:WRITE_LOGS_TO_DB, file(./.env/env.${self:custom.local_env}.json):WRITE_LOGS_TO_DB}

package:
  patterns:
    - '!src/**'

plugins:
  - serverless-domain-manager
  - serverless-apigw-binary

functions:
  app:
    handler: dist/slsapp.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'